Because the stocks in our portfolio are volatile. When we regress them against the fama-french factors, we may underestimate them. Thus we regress them against the current factors and their lagged versions. 
This files contains the code to create the lagged factors.

In [2]:
import pandas as pd
import numpy as np


fama_french_factor_file = '../data/F-F_Research_Data_Factors_daily.CSV'

fama_french_factor = pd.read_csv(fama_french_factor_file)
# Rename Unamed: 0 to date
fama_french_factor = fama_french_factor.rename(columns={'Unnamed: 0': 'date'})
display(fama_french_factor)

           date  Mkt-RF   SMB   HML     RF
0      19260701    0.10 -0.25 -0.27  0.009
1      19260702    0.45 -0.33 -0.06  0.009
2      19260706    0.17  0.30 -0.39  0.009
3      19260707    0.09 -0.58  0.02  0.009
4      19260708    0.21 -0.38  0.19  0.009
...         ...     ...   ...   ...    ...
25394  20221223    0.51 -0.60  1.15  0.016
25395  20221227   -0.51 -0.73  1.42  0.016
25396  20221228   -1.23 -0.25 -0.29  0.016
25397  20221229    1.87  1.27 -1.07  0.016
25398  20221230   -0.22  0.11 -0.03  0.016

[25399 rows x 5 columns]

In [3]:
# Parse date
fama_french_factor['date'] = pd.to_datetime(fama_french_factor['date'], format='%Y%m%d')

In [6]:
# Create lagged factors
fama_french_factor['Mkt-RF_lag1'] = fama_french_factor['Mkt-RF'].shift(1)
fama_french_factor['SMB_lag1'] = fama_french_factor['SMB'].shift(1)
fama_french_factor['HML_lag1'] = fama_french_factor['HML'].shift(1)

# Drop first row
fama_french_factor = fama_french_factor.dropna()

In [7]:
display(fama_french_factor)

            date  Mkt-RF   SMB   HML     RF  Mkt-RF_lag1  SMB_lag1  HML_lag1
1     1926-07-02    0.45 -0.33 -0.06  0.009         0.10     -0.25     -0.27
2     1926-07-06    0.17  0.30 -0.39  0.009         0.45     -0.33     -0.06
3     1926-07-07    0.09 -0.58  0.02  0.009         0.17      0.30     -0.39
4     1926-07-08    0.21 -0.38  0.19  0.009         0.09     -0.58      0.02
5     1926-07-09   -0.71  0.43  0.57  0.009         0.21     -0.38      0.19
...          ...     ...   ...   ...    ...          ...       ...       ...
25394 2022-12-23    0.51 -0.60  1.15  0.016        -1.52      0.10      0.37
25395 2022-12-27   -0.51 -0.73  1.42  0.016         0.51     -0.60      1.15
25396 2022-12-28   -1.23 -0.25 -0.29  0.016        -0.51     -0.73      1.42
25397 2022-12-29    1.87  1.27 -1.07  0.016        -1.23     -0.25     -0.29
25398 2022-12-30   -0.22  0.11 -0.03  0.016         1.87      1.27     -1.07

[25398 rows x 8 columns]

In [8]:
# Save to CSV and Pickle
fama_french_factor.to_csv('../data/fama_french_factor_lagged.csv', index=False)
fama_french_factor.to_pickle('../data/fama_french_factor_lagged.pkl')